version: "3"
volumes:
#  postfix:
  log:
services:
  postfix-relay:
    image: postfix-relay:latest
    container_name: postfix-relay
    environment:
      - TZ=Asia/Hong_Kong
      - MYHOSTNAME=smtp-out.contoso.com
      - MYDOMAIN=contoso.com      
#      - MYNETWORKS=127.0.0.1, 192.168.1.44
      - RELAYHOST=smtpo.hsbc.com.hk
#      - "ALIASES=alwaysbcc: journal@contoso.com, peter.pen@contoso.com / elon.musk: elon.musk@tasla.com"                # Where "/" as line seperator
#      - ALWAYS_BCC=alwaysbcc
      - TRANSPORT=tasla.com smtp:[mail.tasla.com]:25, db.com smtp:[mail.db.com]:25                                       
#      - HEADER_CHECKS=1                                                                                                 # Unset or 0=Disable
#      - RATE_LIMIT=20                                                                                                   # Unset or 0=Unlimited
#      - DEFAULT_SMTP_PORT=2525                                                                                          # Unset will be port 25
#      - DNS=192.168.1.1, 8.8.8.8
      - PWCHECK_METHOD=SHADOW                                                                                            # Available options; "LDAP", "SHADOW" or not set
#      - LDAP_SERVERS=dc01.contoso.com                                                                                   # Use when PWCHECK_METHOD=LDAP
#      - LDAP_SEARCH_BASE=DC=CONTOSO,DC=COM                                                                              # Use when PWCHECK_METHOD=LDAP
#      - LDAP_BIND_DN=CN=Postfix_Service,OU=Service,OU=Users,OU=HK,DC=CONTOSO,DC=COM                                     # Use when PWCHECK_METHOD=LDAP
#      - LDAP_PASSWORD=6ubC%&VAf5CK94                                                                                    # Use when PWCHECK_METHOD=LDAP
       - SHADOW_USERNAME=smtp-out                                                                                        # Use when PWCHECK_METHOD=SHADOW
       - SHADOW_PASSWORD=Dax852EB!                                                                                       # Use when PWCHECK_METHOD=SHADOW
#      - "SYSLOG=@syslog.contoso.com:514"                                                                                # @=UDP, @@=TCP       
    volumes:
#      - postfix:/etc/postfix
      - log:/var/log
    ports:
      - 25:25
    restart: unless-stopped
