version: "3"
volumes:
#  postfix:
  log:
services:
  postfix-relay:
    image: williswschan/postfix-relay:latest
    container_name: postfix-relay
    environment:
      - TZ=Asia/Hong_Kong
      - MYHOSTNAME=smtp-out.contoso.com
      - MYNETWORKS=
      - RELAYHOST=
      - "ALIASES=alwaysbcc:  journal@contoso.com"
      - ALWAYS_BCC=alwaysbcc
      - TRANSPORT=contoso.com  smtp:[mail.contoso.com]:25
      - LDAP_SERVERS=dc01.contoso.com
      - LDAP_SEARCH_BASE=DC=CONTOSO,DC=COM
      - LDAP_BIND_DN=CN=Postfix_Service,OU=Service,OU=Users,OU=HK,DC=CONTOSO,DC=COM
      - LDAP_PASSWORD=7ubT%&VAf6BK85
      - HEADER_CHECKS=1                  # 1=Enable, 0=Disable      
    volumes:
#      - postfix:/etc/postfix
      - log:/var/log
    ports:
      - 25:25
    restart: unless-stopped
